swagger: "2.0"
info:
  description: Godo is a todo list
  title: Godo
  version: 1.0.0
consumes:
  - application/json
produces:
  - application/json
schemes:
  - http
paths:
  /:
    get:
      tags:
        - tasks
      responses:
        200:
          schema:
            type: array
            items:
              $ref: "#/definitions/getTasksResponse"
        default:
          schema:
            $ref: "#/definitions/response"
    post:
      tags:
        - tasks
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/createTaskRequest"
      responses:
        201:
          schema:
            $ref: "#/definitions/createTaskResponse"
        400:
          schema:
            $ref: "#/definitions/response"
        default:
          schema:
            $ref: "#/definitions/response"
  /{id}:
    get:
      tags:
        - tasks
      parameters:
        - name: id
          in: path
          required: true
          type: integer
      responses:
        200:
          schema:
            $ref: "#/definitions/getTaskResponse"
        404:
          schema:
            $ref: "#/definitions/response"
        default:
          schema:
            $ref: "#/definitions/response"
    put:
      tags:
        - tasks
      parameters:
        - name: id
          in: path
          required: true
          type: integer
        - name: body
          in: body
          schema:
            $ref: "#/definitions/createTaskRequest"
      responses:
        200:
          schema:
            $ref: "#/definitions/createTaskResponse"
        400:
          schema:
            $ref: "#/definitions/response"
        404:
          schema:
            $ref: "#/definitions/response"
        default:
          schema:
            $ref: "#/definitions/response"
  /{id}/completed:
    post:
      tags:
        - tasks
      parameters:
        - name: id
          in: path
          required: true
          type: integer
      responses:
        200:
          schema:
            $ref: "#/definitions/getTaskResponse"
        404:
          schema:
            $ref: "#/definitions/response"
        default:
          schema:
            $ref: "#/definitions/response"
    delete:
      tags:
        - tasks
      parameters:
        - name: id
          in: path
          required: true
          type: integer
      responses:
        200:
          schema:
            $ref: "#/definitions/getTaskResponse"
        404:
          schema:
            $ref: "#/definitions/response"
        default:
          schema:
            $ref: "#/definitions/response"
definitions:
  task:
    type: object
    properties:
      id:
        type: integer
      description:
        type: string
      completed:
        type: boolean
  response:
    type: object
    properties:
      data:
        type: object
      errors:
        type: array
        items:
          type: string
  getTaskResponse:
    type: object
    properties:
      data:
        $ref: "#/definitions/task"
      errors:
        type: array
        items:
          type: string
  getTasksResponse:
    type: object
    properties:
      data:
        type: array
        items:
          $ref: "#/definitions/task"
      errors:
        type: array
        items:
          type: string
  createTaskRequest:
    type: object
    properties:
      description:
        type: string
  createTaskResponse:
    type: object
    properties:
      data:
        $ref: "#/definitions/task"
      errors:
        type: array
        items:
          type: string
