swagger: "2.0"
info:
  description: Godo is a todo list
  title: Godo
  version: 1.0.0
consumes:
  - application/json
produces:
  - application/json
schemes:
  - http
paths:
  /:
    get:
      tags:
        - tasks
      responses:
        200:
          schema:
            type: array
            items:
              $ref: "#/definitions/task"
        default:
          schema:
            $ref: "#/definitions/error"
    post:
      tags:
        - tasks
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/createTask"
      responses:
        201:
          schema:
            $ref: "#/definitions/task"
        400:
          schema:
            $ref: "#/definitions/error"
        default:
          schema:
            $ref: "#/definitions/error"
definitions:
  task:
    type: object
    properties:
      id:
        type: integer
        format: int64
      description:
        type: string
      completed:
        type: boolean
  createTask:
    type: object
    properties:
      description:
        type: string
  error:
    type: object
    properties:
      errors:
        type: array
        items:
          type: string
