swagger: "2.0"
info:
  description: Godo is a todo list
  title: Godo
  version: 1.0.0
consumes:
  - application/json
produces:
  - application/json
schemes:
  - http
paths:
  /:
    get:
      tags:
        - tasks
      responses:
        200:
          description: list the tasks
          schema:
            type: array
            items:
              $ref: "#/definitions/task"
definitions:
  task:
    type: object
    required:
      - description
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      description:
        type: string
        minLength: 1
      completed:
        type: boolean
